<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="lidar_sensor" params="
        prefix:=''
        parent:='base_link'
        frame_id:='laser_frame'
        xyz_offset:='0 0 0'
        rpy_offset:='0 0 0'
        mesh_xyz_offset:='0 0 0'
        mesh_rpy_offset:='${-M_PI/2} 0 0'
        mesh_scale:='0.001 0.001 0.001'
        collision_xyz_offset:='0 0 0'
        collision_rpy_offset:='0 0 0'
        inertial_xyz_offset:='0 0 0'
        inertial_rpy_offset:='0 0 0'
        lidar_width:=0.077
        lidar_height:=0.0398
        mass:=0.185
        material_name:='rplidar_black'
        material_color:='0.1 0.1 0.1 1'
        gazebo_material_ambient:='0.1 0.1 0.1 1'
        gazebo_material_diffuse:='0.1 0.1 0.1 1'
        gazebo_material_specular:='0.1 0.1 0.1 1'
        update_rate:=10
        ray_count:=720
        min_angle:='-3.14159'
        max_angle:='3.14159'
        min_range:='0.20'
        max_range:='30.0'
        range_resolution:='0.013'
        topic_name:='scan'
        always_on:=true
        visualize:=false
        enable_collision:=false">

        <link name="${prefix}${frame_id}">
        <visual>
            <origin xyz="${mesh_xyz_offset}" rpy="${mesh_rpy_offset}"/>
            <geometry>
            <cylinder radius="${lidar_width/2}" length="${lidar_height}"/>
            </geometry>
            <material name="${material_name}">
            <color rgba="${material_color}"/>
            </material>
        </visual>

        <xacro:if value="${enable_collision}">
            <collision>
            <origin xyz="${collision_xyz_offset}" rpy="${collision_rpy_offset}"/>
            <geometry>
                <cylinder radius="${lidar_width/2}" length="${lidar_height}"/>
            </geometry>
            </collision>
        </xacro:if>

        <xacro:cylinder_inertia
            m="${mass}"
            r="${lidar_width/2}"
            l="${lidar_height}"
            o_xyz="${inertial_xyz_offset}"
            o_rpy="${inertial_rpy_offset}"/>
        </link>

        <joint name="${prefix}${frame_id}_joint" type="fixed">
        <parent link="${prefix}${parent}"/>
        <child link="${prefix}${frame_id}" />
        <origin xyz="${xyz_offset}" rpy="${rpy_offset}"/>
        </joint>

    </xacro:macro> <!-- end lidar_sensor -->
</robot>
